name = "react-task-tracker"
compatibility_date = "2026-01-16"

pages_build_output_dir = "build"

[env.production.vars]
NODE_VERSION = "24.13.0"

[env.production]
[[env.production.d1_databases]]
binding = "TASK_DB"
database_name = "task-tracker"
database_id = "45db1dce-f87b-4a63-be1a-bf090f7c9935"
